version: "3.9"

services:
  db:
    image: postgres:14-alpine

    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=plannerpostgres

    volumes:
      - ./data/db:/var/lib/postgresql/data

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    ports:
      - "3000:3000"

    volumes:
      - /app/frontend/node_modules

    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    ports:
      - "8001:8000"

    volumes:
      - ./backend:/app/backend

    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=plannerpostgres
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres

    depends_on:
      - db
